name: CI Pipeline

on:
  push:
    branches: ["main", "feature/**", "bugfix/**"]
  # Habilitando gatilho para execução manual
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build with Maven
        run: mvn clean verify
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=sonnesen_fiap-product-api \
            -Dsonar.organization=sonnesen \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports